parameters:
    # change this if you want to use a different locale than the one gotten from the current siteaccess
    ez_loremipsum_bundle.faker.locale: ~

    # add custom providers to faker. These classes are expected to have a specific constructor signature
    ez_loremipsum_bundle.faker.providers:
        - "Kaliop\\eZLoremIpsumBundle\\Faker\\Provider\\Picture"
        - "Kaliop\\eZLoremIpsumBundle\\Faker\\Provider\\XmlText"
        - "Kaliop\\eZLoremIpsumBundle\\Faker\\Provider\\WordList"
        - "Kaliop\\eZLoremIpsumBundle\\Faker\\Provider\\PdfFile"
        - "Kaliop\\eZLoremIpsumBundle\\Faker\\Provider\\RichText"

    ez_loremipsum_bundle.reference_resolver.faker.class: Kaliop\eZLoremIpsumBundle\Core\ReferenceResolver\FakerResolver

services:

    ez_loremipsum_bundle.reference_resolver.faker:
        class: '%ez_loremipsum_bundle.reference_resolver.faker.class%'
        arguments:
            - '@ezpublish.config.resolver'
            - '@ez_migration_bundle.reference_resolver.customreference'
            - '%ez_loremipsum_bundle.faker.locale%'
            - '%ez_loremipsum_bundle.faker.providers%'
        tags:
            - { name: ez_migration_bundle.reference_resolver.customreference }
